% Hello there. This is an extension of the phase-Amplitude bifurcation 
% diagram in which we analyze the mean square fluctuation of the impact 
% phases in a long-run solution of the bouncing ball mapping.
% 
% The inputs are as follows:
% 
%       PtP:    stands for Points_to_Plot; the points on the bifurcation 
%               plot generated by the bifurcationDiagram.m script

function phaseVariance(PtP)
    Amps = PtP(:,1);
    AmpList = unique(Amps);
    phasePlot = [];
    Phases = PtP(:,2);
    for A = AmpList' %from column to row vector
        phaseList = Phases(Amps == A);
        phaseVariance = std(phaseList) ^ 2;
        phasePlot = [phasePlot; phaseVariance];
    end

    %plot the variance vs. Amplitude
    figure(3),clf
    plot(AmpList,phasePlot,"k.",LineWidth=2)
    grid on
    title("Phase Variance vs. Amplitude")
    xlabel("Amplitudes (mm)"); ylabel("Impact Phase Variance")

    %generate a derivative plot using central diffs
    deriv = (phasePlot(3:end) - phasePlot(1:end-2)) ./ ...
        (AmpList(3:end) - AmpList(1:end-2));

    %plot the "derivative" of the associated scatter plot
    figure(4),clf
    scatter(AmpList(2:end-1),deriv,2.5,'filled','black')
    grid on
    title("The Derivative of Phase Variance vs. Amplitude")
    xlabel("Amplitudes (mm)"); ylabel("d(Variance)/d(Amplitude)")
end